research_task:
  description: >
    Execute multidimensional investigation of {topic} including:
    - Technical specifications/developments
    - Market/industry impact analysis
    - Social/cultural implications
    - Temporal analysis (historical context + 2025+ projections)
    - Cross-domain connections
    Validate source credibility and maintain controversy balance
  expected_output: >
    Structured knowledge package containing:
    - 5 Key Insights (categorized by impact level)
    - Technical Development Timeline (2020-2025+)
    - Stakeholder Analysis Matrix
    - 3 Alternative Future Scenarios
    - Source Reliability Index (1-5 scale)
    Format: JSON structure with markdown-compatible formatting
  agent: researcher

reporting_task:
  description: >
    Synthesize research package into context-aware intelligence brief.
    Auto-determine optimal presentation format based on {topic} characteristics:
    - Technical Deep Dive (for engineering/science topics)
    - Policy Brief (for social/government topics)
    - Strategic Roadmap (for business/industry topics)
    Include dynamic visualizations proposals and implementation checklists
  expected_output: >
    Adaptive report containing:
    - Executive Summary (TL;DR)
    - Core Analysis (modular sections)
    - Comparative Scenario Analysis
    - Actionable Recommendations
    - Temporal Projection Model
    - Dynamic Visualization Mockups (Mermaid/Chart syntax)
    Format: Markdown document with section collapse/expand features
  agent: reporting_analyst