# tasks_Blogger.yaml
identify_trending_topics:
  description: >
    Detect authentic trends across:
    - Search patterns (Google Trends/Bing/YouTube)
    - Social conversations (Reddit/Twitter/Forums)
    - News cycle analysis
    - Cultural undercurrents (meme tracking, podcast mentions)
    Filter out manufactured trends and identify sustainable topics
  expected_output: >
    Trend Briefing Dossier containing:
    - 5 Core Trends with Cultural Relevance Scores (1-10)
    - Trend Origin Analysis
    - Cross-Platform Engagement Metrics
    - Predicted Longevity Estimates
    Format: JSON with markdown annotations
  agent: trend_finder

research_topics:
  description: >
    Conduct multi-source verification research including:
    - Academic paper analysis
    - Primary source validation
    - Expert opinion cross-checking
    - Historical context alignment
    Generate accuracy confidence levels for all facts
  expected_output: >
    Verified Research Package:
    - Fact-Check Matrix (Claims vs Verification Sources)
    - Contextual Backgrounders
    - Controversy Flags (areas needing careful handling)
    - Visual Evidence Repository (charts/images/video clips)
    Format: Structured Markdown with source annotations
  agent: researcher

analyze_data:
  description: >
    Create narrative blueprints optimized for:
    - Cognitive flow patterns
    - Attention span matching
    - Knowledge scaffolding
    - Emotional engagement peaks
    Develop content warnings for complex sections
  expected_output: >
    Story Architecture Document containing:
    - Narrative Flow Map
    - Key Concept Dependency Graph
    - Analogies Bank (complex idea simplifications)
    - Engagement Hotspots Plan
    Format: MermaidJS diagrams + explanatory text
  agent: reporting_analyst

create_content:
  description: >
    Compose blog post using:
    - Conversational knowledge transfer techniques
    - Readability engineering (Flesch-Kincaid optimization)
    - SEO-natural keyword integration
    - Multi-format content blending (text, visual metaphors, data snapshots)
    Include interactive elements for digital consumption
  expected_output: >
    Publication-Ready Article with:
    - Adaptive Introduction (multiple hook options)
    - Modular Content Sections (skimmable yet deep)
    - Contextual Callouts (expert quotes, data highlights)
    - Reader Journey Checkpoints (comprehension verification)
    - Natural Language FAQs (anticipating questions)
    Format: Enhanced Markdown with semantic HTML5 elements
  agent: content_creator

workflow:
  - from: identify_trending_topics
    to: research_topics
    review: >
      Quality check for trend authenticity and cultural alignment
  - from: research_topics
    to: analyze_data
    review: >
      Verify accuracy scores and source diversity
  - from: analyze_data
    to: create_content
    review: >
      Validate narrative flow against cognitive models